export const funFacts = [
	'Creepers were created by a coding error when trying to create pigs.',
	'Endermen can pick up and move blocks.',
	'Ghasts float and shoot fireballs in the Nether.',
	'Mooshrooms are mushroom-covered cows found in mushroom biomes.',
	'A compass points to the player’s spawn point, not north.',
	"Naming a sheep 'jeb_' causes its wool to cycle colors.",
	'Silverfish hide inside certain stone blocks and attack players.',
	'Powdered snow can be walked on if wearing leather boots.',
	"Naming mobs 'Dinnerbone' or 'Grumm' flips them upside down.",
	'The End dimension contains the Ender Dragon boss.',
	'Zombies are hostile mobs that spawn in dark areas.',
	'Witches throw harmful splash potions at players.',
	'Snow golems throw snowballs but deal no damage.',
	'Baby zombies move faster than adult zombies.',
	'Music discs can be played in jukeboxes.',
	'Villagers have professions and use workstations.',
	'The void kills players and entities instantly if they fall into it.',
	'Slimes spawn in slime chunks and swamp biomes.',
	'Parrots can imitate sounds of nearby mobs.',
	'Turtle eggs hatch baby turtles after some time.',
	'Bats are passive mobs that spawn in dark caves.',
	'Pandas have different personalities and behaviors.',
	'Foxes can hold items in their mouths.',
	'Bees can pollinate flowers and produce honey.',
	'Axolotls can be bred and used in combat.',
	'Glow squids emit light and drop glow ink sacs.',
	'Llamas can be equipped with chests and used as pack animals.',
	'Dolphins can lead players to shipwrecks and underwater ruins.',
	'Striders can walk on lava and are found in the Nether.'
]
